name: easy_mall_shop
description: A new Online shop project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  list_tile_switch: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_staggered_grid_view: ^0.4.0
  badges: ^2.0.1
  backdrop: ^0.6.2
  carousel_pro: ^1.0.0
  ffi: ^1.1.2
  flutter_swiper: ^1.1.6
  cached_network_image: ^3.0.0
  animated_text_kit: ^4.2.1
  wave: ^0.2.0
  image_picker: ^0.8.2
  ionicons: ^0.1.2
  flutter_launcher_name: ^0.0.1
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  google_sign_in: ^5.0.5
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  uuid: ^3.0.4
  fluttertoast: ^8.0.8
  http: ^0.13.3
  stripe_payment: ^1.1.4
  progress_dialog: ^1.2.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter pub run flutter_launcher_name:main to change app name
flutter_launcher_name:
  name: "Easy Mall"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/playstore.png
    - assets/images/emptycart.png
    - assets/images/caro1.jpg
    - assets/images/caro2.jpg
    - assets/images/caro3.jpg
    - assets/images/caro4.jpg
    - assets/images/caro5.jpg
    - assets/images/caro6.jpg
    - assets/images/caro7.jpg
    - assets/images/addidas.jpg
    - assets/images/apple.webp
    - assets/images/dell.jpg
    - assets/images/hp.jpg
    - assets/images/huawei.png
    - assets/images/nike.jpg
    - assets/images/samsung.jpg
    - assets/images/catbeauty.jpg
    - assets/images/catclothes.jpg
    - assets/images/catfurniture.jpg
    - assets/images/catlaptop.jpg
    - assets/images/catmatches.jpg
    - assets/images/cataf.jpg
    - assets/images/cataf2.png
    - assets/images/catshoes.jpg
    - assets/images/empty-wishlist.png
